## Устанавливаем HMMER

In [ ]:
%%bash
apt-get update -qq
apt-get install -y hmmer

Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libdivsufsort3
Suggested packages:
  hmmer-doc
The following NEW packages will be installed:
  hmmer libdivsufsort3
0 upgraded, 2 newly installed, 0 to remove and 19 not upgraded.
Need to get 1,198 kB of archives.
After this operation, 7,621 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libdivsufsort3 amd64 2.0.1-5 [42.8 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/universe amd64 hmmer amd64 3.3.2+dfsg-1 [1,155 kB]
Fetched 1,198 kB in 0s (8,862 kB/s)
Selecting previously unselected package libdivsufsort3:amd64.
(Reading database ... 118243 files and directories currently installed.)
Preparing to unpack .../libdivsufsort3_2.0.1-5_amd64.deb ...
Unpacking libdivsufsort3:amd64 (2.0.1-5) ...
Selecting previously unselected package hmmer.
Preparing to unpack .../hmmer_3.3.2+dfsg-1_amd64.deb ...
Unpacking hmmer (3.3.2+dfsg-1) ...
Setting up libdivsufsort3:amd64 (2.0.1-5) ...
Setting up hmmer (3.3.2+dfsg-1) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.13) ...
/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)

In [ ]:
%%bash

wget -nc http://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam35.0/Pfam-A.hmm.gz

gunzip -f Pfam-A.hmm.gz

hmmpress Pfam-A.hmm

hmmfetch --index Pfam-A.hmm

Working...    done.
Pressed and indexed 19632 HMMs (19632 names and 19632 accessions).
Models pressed into binary file:   Pfam-A.hmm.h3m
SSI index for binary model file:   Pfam-A.hmm.h3i
Profiles (MSV part) pressed into:  Pfam-A.hmm.h3f
Profiles (remainder) pressed into: Pfam-A.hmm.h3p
Working...    done.
Indexed 19632 HMMs (19632 names and 19632 accessions).
SSI index written to file Pfam-A.hmm.h3m.ssi

--2026-06-09 18:57:36--  http://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam35.0/Pfam-A.hmm.gz
Resolving ftp.ebi.ac.uk (ftp.ebi.ac.uk)... 193.62.193.165
Connecting to ftp.ebi.ac.uk (ftp.ebi.ac.uk)|193.62.193.165|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 293000230 (279M) [application/x-gzip]
Saving to: ‘Pfam-A.hmm.gz’

     0K .......... .......... .......... .......... ..........  0%  185K 25m45s
    50K .......... .......... .......... .......... ..........  0%  371K 19m18s
   100K .......... .......... .......... .......... ..........  0%  197M 12m52s
   150K .......... .......... .......... .......... ..........  0%  370K 12m52s
   200K .......... .......... .......... .......... ..........  0%  370K 12m52s
   250K .......... .......... .......... .......... ..........  0% 53.6M 10m44s
   300K .......... .......... .......... .......... ..........  0%  158M 9m12s
   350K .......... .......... .......... .......... ..........  0%  368K 9m40s
   400K .......... .......... .......... .......... ..........  0% 96.1M 8m36s
   450K .......... .......... .......... .......... ..........  0%  291M 7m44s
   500K .......... .......... .......... .......... ..........  0%  371K 8m12s
   550K .......... .......... .......... .......... ..........  0%  285M 7m31s
   600K .......... .......... .......... .......... ..........  0%  370K 7m56s
   650K .......... .......... .......... .......... ..........  0%  369K 8m17s
   700K .......... .......... .......... .......... ..........  0%  270M 7m44s
   750K .......... .......... .......... .......... ..........  0%  315M 7m15s
   800K .......... .......... .......... .......... ..........  0%  369K 7m35s
   850K .......... .......... .......... .......... ..........  0% 88.3M 7m9s
   900K .......... .......... .......... .......... ..........  0%  373M 6m47s
   950K .......... .......... .......... .......... ..........  0%  361K 7m6s
  1000K .......... .......... .......... .......... ..........  0%  363K 7m23s
  1050K .......... .......... .......... .......... ..........  0% 29.9M 7m3s
  1100K .......... .......... .......... .......... ..........  0%  238M 6m45s
  1150K .......... .......... .......... .......... ..........  0%  374K 7m0s
  1200K .......... .......... .......... .......... ..........  0%  238M 6m43s
  1250K .......... .......... .......... .......... ..........  0%  370K 6m57s
  1300K .......... .......... .......... .......... ..........  0%  371K 7m10s
  1350K .......... .......... .......... .......... ..........  0%  231M 6m54s
  1400K .......... .......... .......... .......... ..........  0%  370K 7m7s
  1450K .......... .......... .......... .......... ..........  0%  277M 6m52s
  1500K .......... .......... .......... .......... ..........  0%  370K 7m4s
  1550K .......... .......... .......... .......... ..........  0%  303M 6m50s
  1600K .......... .......... .......... .......... ..........  0%  369K 7m1s
  1650K .......... .......... .......... .......... ..........  0%  183M 6m49s
  1700K .......... .......... .......... .......... ..........  0%  368K 6m59s
  1750K .......... .......... .......... .......... ..........  0%  254M 6m47s
  1800K .......... .......... .......... .......... ..........  0%  370K 6m57s
  1850K .......... .......... .......... .......... ..........  0%  370K 7m6s
  1900K .......... .......... .......... .......... ..........  0%  213M 6m55s
  1950K .......... .......... .......... .......... ..........  0%  369K 7m4s
  2000K .......... .......... .......... .......... ..........  0%  376M 6m54s
  2050K .......... .......... .......... .......... ..........  0%  409M 6m44s
  2100K .......... .......... .......... .......... ..........  0%  370K 6m52s
  2150K .......... .......... .......... .......... ..........  0%  370K 7m0s
  2200K .......... .......... .......... .......... ..........  0%  140M 6m51s
  2250K .......... .......... .......... .......... ..........  0%  243M 6m42s
  2300K .......... .......... .......... .......... ..........  0%  369K 6m50s
  2350K .......... .......... .......... .......... ..........  0%  337M 6m41s
  2400K .......... .......... .......... .......... ..........  0%  370K 6m48s
  2450K .......... .......... .......... .......... ..........  0%  369K 6m55s
  2500K .......... .......... .......... .......... ..........  0%  309M 6m47s
  2550K .......... .......... .......... .......... ..........  0%  371K 6m54s
  2600K .......... .......... .......... .......... ..........  0%  252M 6m46s
  2650K .......... .......... .......... .......... ..........  0%  368K 6m53s
  2700K .......... .......... .......... .......... ..........  0%  367K 6m59s
  2750K .......... .......... .......... .......... ..........  0%  343M 6m52s
  2800K .......... .......... .......... .......... ..........  0%  370K 6m58s
  2850K .......... .......... .......... .......... ..........  1%  365K 7m4s
  2900K .......... .......... .......... .......... ..........  1%  212M 6m57s
  2950K .......... .......... .......... .......... ..........  1%  280M 6m50s
  3000K .......... .......... .......... .......... ..........  1%  371K 6m56s
  3050K .......... .......... .......... .......... ..........  1%  346M 6m49s
  3100K .......... .......... .......... .......... ..........  1%  370K 6m54s
  3150K .......... .......... .......... .......... ..........  1%  422M 6m48s
  3200K .......... .......... .......... .......... ..........  1%  370K 6m53s
  3250K .......... .......... .......... .......... ..........  1%  407M 6m47s
  3300K .......... .......... .......... .......... ..........  1%  370K 6m52s
  3350K .......... .......... .......... .......... ..........  1%  370K 6m57s
  3400K .......... .......... .......... .......... ..........  1%  157M 6m51s
  3450K .......... .......... .......... .......... ..........  1%  156M 6m45s
  3500K .......... .......... .......... .......... ..........  1%  369K 6m50s
  3550K .......... .......... .......... .......... ..........  1%  380M 6m44s
  3600K .......... .......... .......... .......... ..........  1%  370K 6m49s
  3650K .......... .......... .......... .......... ..........  1%  272M 6m44s
  3700K .......... .......... .......... .......... ..........  1%  370K 6m48s
  3750K .......... .......... .......... .......... ..........  1%  369K 6m53s
  3800K .......... .......... .......... .......... ..........  1%  150M 6m48s
  3850K .......... .......... .......... .......... ..........  1%  301M 6m42s
  3900K .......... .......... .......... .......... ..........  1%  369K 6m47s
  3950K .......... .......... .......... .......... ..........  1%  319M 6m42s
  4000K .......... .......... .......... .......... ..........  1%  288M 6m37s
  4050K .......... .......... .......... .......... ..........  1%  370K 6m41s
  4100K .......... .......... .......... .......... ..........  1%  225M 6m36s
  4150K .......... .......... .......... .......... ..........  1%  356M 6m31s
  4200K .......... .......... .......... .......... ..........  1%  370K 6m36s
  4250K .......... .......... .......... .......... ..........  1%  285M 6m31s
  4300K .......... .......... .......... .......... ..........  1%  367K 6m35s
  4350K .......... .......... .......... .......... ..........  1%  262M 6m31s
  4400K .......... .......... .......... .......... ..........  1%  368K 6m35s
  4450K .......... .......... .......... .......... ..........  1%  370K 6m39s
  4500K .......... .......... .......... .......... ..........  1%  216M 6m34s
  4550K .......... .......... .......... .......... ..........  1%  369K 6m38s
  4600K .......... .......... .......... .......... ..........  1%  145M 6m34s
  4650K .......... .......... .......... .......... ..........  1%  186M 6m30s
  4700K .......... .......... .......... .......... ..........  1%  370K 6m34s
  4750K .......... .......... .......... .......... ..........  1%  370K 6m37s
  4800K .......... .......... .......... .......... ..........  1%  286M 6m33s
  4850K .......... .......... .......... .......... ..........  1%  370K 6m37s
  4900K .......... .......... .......... .......... ..........  1%  185M 6m33s
  4950K .......... .......... .......... .......... ..........  1%  286M 6m29s
  5000K .......... .......... .......... .......... ..........  1%  370K 6m32s
  5050K .......... .......... .......... .......... ..........  1%  319M 6m29s
  5100K .......... .......... .......... .......... ..........  1%  370K 6m32s
  5150K .......... .......... .......... .......... ..........  1%  350M 6m28s
  5200K .......... .......... .......... .......... ..........  1%  368K 6m32s
  5250K .......... .......... .......... .......... ..........  1% 87.0M 6m28s
  5300K .......... .......... .......... .......... ..........  1%  263M 6m24s
  5350K .......... .......... .......... .......... ..........  1%  368K 6m28s
  5400K .......... .......... .......... .......... ..........  1%  395M 6m24s
  5450K .......... .......... .......... .......... ..........  1%  368K 6m28s
  5500K .......... .......... .......... .......... ..........  1%  365K 6m31s
  5550K .......... .......... .......... .......... ..........  1%  329M 6m27s
  5600K .......... .......... .......... .......... ..........  1%  369K 6m31s
  5650K .......... .......... .......... .......... ..........  1%  370K 6m34s
  5700K .......... .......... .......... .......... ..........  2%  265M 6m30s
  5750K .......... .......... .......... .......... ..........  2%  371K 6m33s
  5800K .......... .......... .......... .......... ..........  2%  291M 6m30s
  5850K .......... .......... .......... .......... ..........  2%  370K 6m33s
  5900K .......... .......... .......... .......... ..........  2%  149M 6m30s
  5950K .......... .......... .......... .......... ..........  2%  370K 6m33s
  6000K .......... .......... .......... .......... ..........  2%  228M 6m29s
  6050K .......... .......... .......... .......... ..........  2%  370K 6m32s
  6100K .......... .......... .......... .......... ..........  2%  338M 6m29s
  6150K .......... .......... .......... .......... ..........  2%  370K 6m32s
  6200K .......... .......... .......... .......... ..........  2%  370K 6m35s
  6250K .......... .......... .......... .......... ..........  2%  304M 6m32s
  6300K .......... .......... .......... .......... ..........  2%  370K 6m34s
  6350K .......... .......... .......... .......... ..........  2%  286M 6m31s
  6400K .......... .......... .......... .......... ..........  2%  343M 6m28s
  6450K .......... .......... .......... .......... ..........  2%  370K 6m31s
  6500K .......... .......... .......... .......... ..........  2%  370K 6m34s
  6550K .......... .......... .......... .......... ..........  2%  156M 6m31s
  6600K .......... .......... .......... .......... ..........  2%  371K 6m33s
  6650K .......... .......... .......... .......... ..........  2%  370K 6m36s
  6700K .......... .......... .......... .......... ..........  2%  178M 6m33s
  6750K .......... .......... .......... .......... ..........  2%  368K 6m35s
  6800K .......... .......... .......... .......... ..........  2%  138M 6m33s
  6850K .......... .......... .......... .......... ..........  2%  150M 6m30s
  6900K .......... .......... .......... .......... ..........  2%  370K 6m32s
  6950K .......... .......... .......... .......... ..........  2%  370K 6m35s
  7000K .......... .......... .......... .......... ..........  2%  223M 6m32s
  7050K .......... .......... .......... .......... ..........  2%  370K 6m34s
  7100K .......... .......... .......... .......... ..........  2%  366M 6m31s
  7150K .......... .......... .......... .......... ..........  2%  332M 6m29s
  7200K .......... .......... .......... .......... ..........  2%  370K 6m31s
  7250K .......... .......... .......... .......... ..........  2%  370K 6m34s
  7300K .......... .......... .......... .......... ..........  2% 40.8M 6m31s
  7350K .......... .......... .......... .......... ..........  2%  218M 6m28s
  7400K .......... .......... .......... .......... ..........  2%  370K 6m31s
  7450K .......... .......... .......... .......... ..........  2%  317M 6m28s
  7500K .......... .......... .......... .......... ..........  2%  370K 6m30s
  7550K .......... .......... .......... .......... ..........  2%  370K 6m33s
  7600K .......... .......... .......... .......... ..........  2%  190M 6m30s
  7650K .......... .......... .......... .......... ..........  2%  230M 6m27s
  7700K .......... .......... .......... .......... ..........  2%  370K 6m30s
  7750K .......... .......... .......... .......... ..........  2%  223M 6m27s
  7800K .......... .......... .......... .......... ..........  2%  370K 6m29s
  7850K .......... .......... .......... .......... ..........  2%  370K 6m32s
  7900K .......... .......... .......... .......... ..........  2%  258M 6m29s
  7950K .......... .......... .......... .......... ..........  2%  238M 6m26s
  8000K .......... .......... .......... .......... ..........  2%  370K 6m29s
  8050K .......... .......... .......... .......... ..........  2%  350M 6m26s
  8100K .......... .......... .......... .......... ..........  2%  370K 6m28s
  8150K .......... .......... .......... .......... ..........  2%  298M 6m26s
  8200K .......... .......... .......... .......... ..........  2%  264M 6m24s
  8250K .......... .......... .......... .......... ..........  2%  370K 6m26s
  8300K .......... .......... .......... .......... ..........  2%  299M 6m23s
  8350K .......... .......... .......... .......... ..........  2%  368K 6m25s
  8400K .......... .......... .......... .......... ..........  2%  370K 6m28s
  8450K .......... .......... .......... .......... ..........  2%  348M 6m25s
  8500K .......... .......... .......... .......... ..........  2%  370K 6m27s
  8550K .......... .......... .......... .......... ..........  3%  341M 6m25s
  8600K .......... .......... .......... .......... ..........  3%  366K 6m27s
  8650K .......... .......... .......... .......... ..........  3%  366K 6m29s
  8700K .......... .......... .......... .......... ..........  3%  304M 6m27s
  8750K .......... .......... .......... .......... ..........  3%  242M 6m25s
  8800K .......... .......... .......... .......... ..........  3%  368K 6m27s
  8850K .......... .......... .......... .......... ..........  3%  262M 6m24s
  8900K .......... .......... .......... .......... ..........  3%  366K 6m26s
  8950K .......... .......... .......... .......... ..........  3%  378M 6m24s
  9000K .......... .......... .......... .......... ..........  3%  366K 6m26s
  9050K .......... .......... .......... .......... ..........  3% 30.2M 6m24s
  9100K .......... .......... .......... .......... ..........  3%  370K 6m26s
  9150K .......... .......... .......... .......... ..........  3%  168M 6m24s
  9200K .......... .......... .......... .......... ..........  3%  340M 6m22s
  9250K .......... .......... .......... .......... ..........  3%  369K 6m24s
  9300K .......... .......... .......... .......... ..........  3%  270M 6m21s
  9350K .......... .......... .......... .......... ..........  3%  197M 6m19s
  9400K .......... .......... .......... .......... ..........  3%  367K 6m21s
  9450K .......... .......... .......... .......... ..........  3%  370K 6m23s
  9500K .......... .......... .......... .......... ..........  3%  205M 6m21s
  9550K .......... .......... .......... .......... ..........  3%  368K 6m23s
  9600K .......... .......... .......... .......... ..........  3%  390M 6m21s
  9650K .......... .......... .......... .......... ..........  3%  370K 6m23s
  9700K .......... .......... .......... .......... ..........  3%  289M 6m21s
  9750K .......... .......... .......... .......... ..........  3%  371K 6m22s
  9800K .......... .......... .......... .......... ..........  3%  309M 6m20s
  9850K .......... .......... .......... .......... ..........  3%  370K 6m22s
  9900K .......... .......... .......... .......... ..........  3%  397M 6m20s
  9950K .......... .......... .......... .......... ..........  3%  367K 6m22s
 10000K .......... .......... .......... .......... ..........  3%  181M 6m20s
 10050K .......... .......... .......... .......... ..........  3%  370K 6m22s
 10100K .......... .......... .......... .......... ..........  3%  389M 6m20s
 10150K .......... .......... .......... .......... ..........  3%  370K 6m22s
 10200K .......... .......... .......... .......... ..........  3%  362M 6m20s
 10250K .......... .......... .......... .......... ..........  3%  370K 6m21s
 10300K .......... .......... .......... .......... ..........  3%  370K 6m23s
 10350K .......... .......... .......... .......... ..........  3%  374M 6m21s
 10400K .......... .......... .......... .......... ..........  3%  370K 6m23s
 10450K .......... .......... .......... .......... ..........  3%  171M 6m21s
 10500K .......... .......... .......... .......... ..........  3%  371K 6m23s
 10550K .......... .......... .......... .......... ..........  3%  215M 6m21s
 10600K .......... .......... .......... .......... ..........  3%  369K 6m22s
 10650K .......... .......... .......... .......... ..........  3%  313M 6m21s
 10700K .......... .......... .......... .......... ..........  3%  366K 6m22s
 10750K .......... .......... .......... .......... ..........  3%  257M 6m20s
 10800K .......... .......... .......... .......... ..........  3%  369K 6m22s
 10850K .......... .......... .......... .......... ..........  3%  368K 6m24s
 10900K .......... .......... .......... .......... ..........  3%  307M 6m22s
 10950K .......... .......... .......... .......... ..........  3%  365K 6m23s
 11000K .......... .......... .......... .......... ..........  3%  365K 6m25s
 11050K .......... .......... .......... .......... ..........  3%  210M 6m23s
 11100K .......... .......... .......... .......... ..........  3%  366K 6m25s
 11150K .......... .......... .......... .......... ..........  3%  237M 6m23s
 11200K .......... .......... .......... .......... ..........  3%  365K 6m25s
 11250K .......... .......... .......... .......... ..........  3%  321M 6m23s
 11300K .......... .......... .......... .......... ..........  3%  369K 6m24s
 11350K .......... .......... .......... .......... ..........  3%  151M 6m23s
 11400K .......... .......... .......... .......... ..........  4%  370K 6m24s
 11450K .......... .......... .......... .......... ..........  4%  276M 6m22s
 11500K .......... .......... .......... .......... ..........  4%  370K 6m24s
 11550K .......... .......... .......... .......... ..........  4%  370K 6m25s
 11600K .......... .......... .......... .......... ..........  4%  401M 6m24s
 11650K .......... .......... .......... .......... ..........  4%  370K 6m25s
 11700K .......... .......... .......... .......... ..........  4%  370K 6m26s
 11750K .......... .......... .......... .......... ..........  4%  140M 6m25s
 11800K .......... .......... .......... .......... ..........  4%  370K 6m26s
 11850K .......... .......... .......... .......... ..........  4%  251M 6m25s
 11900K .......... .......... .......... .......... ..........  4%  368M 6m23s
 11950K .......... .......... .......... .......... ..........  4%  370K 6m24s
 12000K .......... .......... .......... .......... ..........  4%  317M 6m23s
 12050K .......... .......... .......... .......... ..........  4%  370K 6m24s
 12100K .......... .......... .......... .......... ..........  4%  285M 6m22s
 12150K .......... .......... .......... .......... ..........  4%  369K 6m24s
 12200K .......... .......... .......... .......... ..........  4%  243M 6m22s
 12250K .......... .......... .......... .......... ..........  4%  129M 6m21s
 12300K .......... .......... .......... .......... ..........  4%  370K 6m22s
 12350K .......... .......... .......... .......... ..........  4%  246M 6m20s

In [5]:
%%bash
ls -lh Pfam-A.hmm*
grep -m 3 "PF00145" Pfam-A.hmm

-rw-r--r-- 1 root root 1.5G Nov 15  2021 Pfam-A.hmm
-rw-r--r-- 1 root root 344M Jun  9 19:03 Pfam-A.hmm.h3f
-rw-r--r-- 1 root root 1.3M Jun  9 19:03 Pfam-A.hmm.h3i
-rw-r--r-- 1 root root 621M Jun  9 19:03 Pfam-A.hmm.h3m
-rw-r--r-- 1 root root 1.3M Jun  9 19:03 Pfam-A.hmm.h3m.ssi
-rw-r--r-- 1 root root 731M Jun  9 19:03 Pfam-A.hmm.h3p
ACC   PF00145.20

In [6]:
pfams = [
    "PF00145",  # DNMT
    "PF01429",  # MBD
    "PF00850",  # HDAC
    "PF00856",  # SET
    "PF06325",  # PRMT
    "PF02182",  # UHRF
    "PF00628",  # PHD
    "PF00439",  # Bromodomain
    "PF00176",  # SNF2
    "PF00271",  # Helicase
    "PF00385",  # Chromodomain
]

full_pfams = []

with open("Pfam-A.hmm") as f:
    for line in f:
        if line.startswith("ACC"):
            acc = line.split()[1]
            if acc.split(".")[0] in pfams:
                full_pfams.append(acc)

full_pfams = sorted(set(full_pfams))

with open("target_pfams_full.txt", "w") as f:
    for acc in full_pfams:
        f.write(acc + "\n")

print("\n".join(full_pfams))

PF00145.20
PF00176.26
PF00271.34
PF00385.27
PF00439.28
PF00628.32
PF00850.22
PF00856.31
PF01429.22
PF02182.20
PF06325.16

In [7]:
%%bash
rm -f epigenetic_domains.hmm

while read pfam
do
    echo "Fetching $pfam"
    hmmfetch Pfam-A.hmm "$pfam" >> epigenetic_domains.hmm
done < target_pfams_full.txt

ls -lh epigenetic_domains.hmm
hmmpress -f epigenetic_domains.hmm
hmmstat epigenetic_domains.hmm

Fetching PF00145.20
Fetching PF00176.26
Fetching PF00271.34
Fetching PF00385.27
Fetching PF00439.28
Fetching PF00628.32
Fetching PF00850.22
Fetching PF00856.31
Fetching PF01429.22
Fetching PF02182.20
Fetching PF06325.16
-rw-r--r-- 1 root root 900K Jun  9 19:25 epigenetic_domains.hmm
Working...    done.
Pressed and indexed 11 HMMs (11 names and 11 accessions).
Models pressed into binary file:   epigenetic_domains.hmm.h3m
SSI index for binary model file:   epigenetic_domains.hmm.h3i
Profiles (MSV part) pressed into:  epigenetic_domains.hmm.h3f
Profiles (remainder) pressed into: epigenetic_domains.hmm.h3p
# hmmstat :: display summary statistics for a profile file
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# idx  name                 accession        nseq eff_nseq      M relent   info p relE compKL
# ---- -------------------- ------------ -------- -------- ------ ------ ------ ------ ------
1      DNA_methylase        PF00145.20         31     3.51    335   0.59   0.57   0.48   0.02
2      SNF2-rel_dom         PF00176.26         19     2.40    318   0.59   0.56   0.44   0.02
3      Helicase_C           PF00271.34        421     6.76    111   0.59   0.59   0.46   0.03
4      Chromo               PF00385.27         82    10.69     54   1.03   0.93   0.93   0.10
5      Bromodomain          PF00439.28         43     7.97     84   0.68   0.64   0.61   0.04
6      PHD                  PF00628.32         71     3.44     52   1.07   0.77   0.97   0.32
7      Hist_deacetyl        PF00850.22         68     2.85    307   0.59   0.57   0.48   0.02
8      SET                  PF00856.31        257    16.98    169   0.59   0.56   0.28   0.01
9      MBD                  PF01429.22         14     4.31     77   0.73   0.68   0.63   0.03
10     SAD_SRA              PF02182.20        161     2.40    153   0.59   0.56   0.45   0.02
11     PrmA                 PF06325.16         27     1.53    295   0.59   0.59   0.51   0.02

In [8]:
import os

for file in os.listdir("/content"):
    if "protein" in file.lower() or file.endswith(".faa"):
        print(file)

GCF_006345805.1_ASM634580v1_protein.faa

In [9]:
%%bash

hmmsearch \
  --domtblout hmmer_epigenetic_domtblout.txt \
  epigenetic_domains.hmm \
  /content/GCF_006345805.1_ASM634580v1_protein.faa \
  > hmmer.log

In [10]:
%%bash
grep -v "^#" hmmer_epigenetic_domtblout.txt | head -30

XP_029649765.1       -           1585 DNA_methylase        PF00145.20   335   2.2e-49  169.6   0.0   1   1     1e-52   2.2e-49  169.6   0.0     3   335  1111  1563  1109  1563 0.79 DNA (cytosine-5)-methyltransferase 1-like [Octopus sinensis]
XP_029639092.2       -            418 DNA_methylase        PF00145.20   335   1.1e-41  144.3   0.0   1   1   5.7e-45   1.3e-41  144.1   0.0     1   331     8   408     8   412 0.77 tRNA (cytosine(38)-C(5))-methyltransferase [Octopus sinensis]
XP_036361613.1       -            612 DNA_methylase        PF00145.20   335     2e-17   64.6   0.0   1   2   1.3e-17     3e-14   54.1   0.0     1   119   330   462   330   492 0.82 DNA (cytosine-5)-methyltransferase 3B isoform X4 [Octopus sinensis]
XP_036361613.1       -            612 DNA_methylase        PF00145.20   335     2e-17   64.6   0.0   2   2    0.0009         2    8.7   0.0   245   331   513   602   476   606 0.75 DNA (cytosine-5)-methyltransferase 3B isoform X4 [Octopus sinensis]
XP_036361611.1       -            748 DNA_methylase        PF00145.20   335   2.7e-17   64.1   0.0   1   2   1.8e-17   4.2e-14   53.7   0.0     1   119   466   598   466   628 0.82 DNA (cytosine-5)-methyltransferase 3B isoform X2 [Octopus sinensis]
XP_036361611.1       -            748 DNA_methylase        PF00145.20   335   2.7e-17   64.1   0.0   2   2    0.0013         3    8.1   0.0   245   331   649   738   619   742 0.75 DNA (cytosine-5)-methyltransferase 3B isoform X2 [Octopus sinensis]
XP_029641100.1       -            749 DNA_methylase        PF00145.20   335   2.7e-17   64.1   0.0   1   2   1.8e-17   4.2e-14   53.6   0.0     1   119   467   599   467   629 0.82 DNA (cytosine-5)-methyltransferase 3B isoform X1 [Octopus sinensis]
XP_029641100.1       -            749 DNA_methylase        PF00145.20   335   2.7e-17   64.1   0.0   2   2    0.0013         3    8.1   0.0   245   331   650   739   620   743 0.75 DNA (cytosine-5)-methyltransferase 3B isoform X1 [Octopus sinensis]
XP_036361607.1       -            749 DNA_methylase        PF00145.20   335   2.7e-17   64.1   0.0   1   2   1.8e-17   4.2e-14   53.6   0.0     1   119   467   599   467   629 0.82 DNA (cytosine-5)-methyltransferase 3B isoform X1 [Octopus sinensis]
XP_036361607.1       -            749 DNA_methylase        PF00145.20   335   2.7e-17   64.1   0.0   2   2    0.0013         3    8.1   0.0   245   331   650   739   620   743 0.75 DNA (cytosine-5)-methyltransferase 3B isoform X1 [Octopus sinensis]
XP_036361608.1       -            749 DNA_methylase        PF00145.20   335   2.7e-17   64.1   0.0   1   2   1.8e-17   4.2e-14   53.6   0.0     1   119   467   599   467   629 0.82 DNA (cytosine-5)-methyltransferase 3B isoform X1 [Octopus sinensis]
XP_036361608.1       -            749 DNA_methylase        PF00145.20   335   2.7e-17   64.1   0.0   2   2    0.0013         3    8.1   0.0   245   331   650   739   620   743 0.75 DNA (cytosine-5)-methyltransferase 3B isoform X1 [Octopus sinensis]
XP_036361609.1       -            749 DNA_methylase        PF00145.20   335   2.7e-17   64.1   0.0   1   2   1.8e-17   4.2e-14   53.6   0.0     1   119   467   599   467   629 0.82 DNA (cytosine-5)-methyltransferase 3B isoform X1 [Octopus sinensis]
XP_036361609.1       -            749 DNA_methylase        PF00145.20   335   2.7e-17   64.1   0.0   2   2    0.0013         3    8.1   0.0   245   331   650   739   620   743 0.75 DNA (cytosine-5)-methyltransferase 3B isoform X1 [Octopus sinensis]
XP_036361610.1       -            749 DNA_methylase        PF00145.20   335   2.7e-17   64.1   0.0   1   2   1.8e-17   4.2e-14   53.6   0.0     1   119   467   599   467   629 0.82 DNA (cytosine-5)-methyltransferase 3B isoform X1 [Octopus sinensis]
XP_036361610.1       -            749 DNA_methylase        PF00145.20   335   2.7e-17   64.1   0.0   2   2    0.0013         3    8.1   0.0   245   331   650   739   620   743 0.75 DNA (cytosine-5)-methyltransferase 3B isoform X1 [Octopus sinensis]
XP_036361612.1       -            738 DNA_methylase        PF00145.20   335   1.8e-14   54.9   0.0   1   1   1.5e-17   3.4e-14   54.0   0.0     1   125   467   600   467   681 0.84 DNA (cytosine-5)-methyltransferase 3B isoform X3 [Octopus sinensis]
XP_029641193.1       -            220 DNA_methylase        PF00145.20   335      0.02   15.3   0.0   1   1   1.4e-05     0.031   14.6   0.0     3    58    56   113    54   125 0.82 rRNA N6-adenosine-methyltransferase METTL5 [Octopus sinensis]
XP_029641194.1       -            220 DNA_methylase        PF00145.20   335      0.02   15.3   0.0   1   1   1.4e-05     0.031   14.6   0.0     3    58    56   113    54   125 0.82 rRNA N6-adenosine-methyltransferase METTL5 [Octopus sinensis]
XP_036357579.1       -            220 DNA_methylase        PF00145.20   335      0.02   15.3   0.0   1   1   1.4e-05     0.031   14.6   0.0     3    58    56   113    54   125 0.82 rRNA N6-adenosine-methyltransferase METTL5 [Octopus sinensis]
XP_036357580.1       -            220 DNA_methylase        PF00145.20   335      0.02   15.3   0.0   1   1   1.4e-05     0.031   14.6   0.0     3    58    56   113    54   125 0.82 rRNA N6-adenosine-methyltransferase METTL5 [Octopus sinensis]
XP_029639525.1       -            261 DNA_methylase        PF00145.20   335     0.071   13.4   0.0   1   1   4.6e-05       0.1   12.9   0.0     2    58   110   170   109   178 0.77 electron transfer flavoprotein beta subunit lysine methyltransferase-like [Octopus sinensis]
XP_029655376.1       -            262 DNA_methylase        PF00145.20   335      0.14   12.5   0.0   1   1    0.0001      0.23   11.8   0.0     4    55    63   115    61   127 0.83 tRNA (guanine(37)-N1)-methyltransferase-like [Octopus sinensis]
XP_029649198.1       -           1527 SNF2-rel_dom         PF00176.26   318   5.7e-90  302.4   0.9   1   1   2.4e-92   9.7e-90  301.7   0.9     1   318   276   720   276   720 0.96 E3 ubiquitin-protein ligase SHPRH [Octopus sinensis]
XP_036367890.1       -           1527 SNF2-rel_dom         PF00176.26   318   5.7e-90  302.4   0.9   1   1   2.4e-92   9.7e-90  301.7   0.9     1   318   276   720   276   720 0.96 E3 ubiquitin-protein ligase SHPRH [Octopus sinensis]
XP_036364112.1       -           1076 SNF2-rel_dom         PF00176.26   318   7.3e-83  279.1   0.7   1   1   5.9e-85   2.4e-82  277.4   0.7     1   317   203   482   203   483 0.94 SWI/SNF-related matrix-associated actin-dependent regulator of chromatin subfamily A member 5 isoform X9 [Octopus sinensis]
XP_036364111.1       -           1077 SNF2-rel_dom         PF00176.26   318   7.3e-83  279.1   0.7   1   1   5.9e-85   2.4e-82  277.4   0.7     1   317   203   482   203   483 0.94 SWI/SNF-related matrix-associated actin-dependent regulator of chromatin subfamily A member 5 isoform X8 [Octopus sinensis]
XP_029644034.1       -           1094 SNF2-rel_dom         PF00176.26   318   7.4e-83  279.1   0.7   1   1   5.9e-85   2.4e-82  277.4   0.7     1   317   220   499   220   500 0.94 SWI/SNF-related matrix-associated actin-dependent regulator of chromatin subfamily A member 5 isoform X6 [Octopus sinensis]
XP_036364110.1       -           1094 SNF2-rel_dom         PF00176.26   318   7.4e-83  279.1   0.7   1   1   5.9e-85   2.4e-82  277.4   0.7     1   317   220   499   220   500 0.94 SWI/SNF-related matrix-associated actin-dependent regulator of chromatin subfamily A member 5 isoform X7 [Octopus sinensis]
XP_029644031.1       -           1111 SNF2-rel_dom         PF00176.26   318   7.6e-83  279.0   0.7   1   1   6.1e-85   2.5e-82  277.3   0.7     1   317   237   516   237   517 0.94 SWI/SNF-related matrix-associated actin-dependent regulator of chromatin subfamily A member 5 isoform X3 [Octopus sinensis]

In [11]:
import pandas as pd

rows = []

with open("hmmer_epigenetic_domtblout.txt") as f:
    for line in f:
        if line.startswith("#"):
            continue

        parts = line.split()

        protein = parts[0]
        domain = parts[3]
        evalue = float(parts[6])

        description = " ".join(parts[22:])

        rows.append(
            {
                "protein": protein,
                "domain": domain,
                "evalue": evalue,
                "description": description,
            }
        )

df = pd.DataFrame(rows)

df = (
    df.sort_values("evalue")
      .drop_duplicates(subset=["protein", "domain"])
)

print(df.shape)
df.head(20)

(1050, 4)

,protein,domain,evalue,description
23,XP_029649198.1,SNF2-rel_dom,5.700000e-90,E3 ubiquitin-protein ligase SHPRH [Octopus sin...
24,XP_036367890.1,SNF2-rel_dom,5.700000e-90,E3 ubiquitin-protein ligase SHPRH [Octopus sin...
1339,XP_029641183.1,Hist_deacetyl,3.000000e-88,histone deacetylase 4 isoform X3 [Octopus sine...
1341,XP_029641185.1,Hist_deacetyl,2.300000e-87,histone deacetylase 4 isoform X5 [Octopus sine...
1344,XP_029641184.1,Hist_deacetyl,2.300000e-87,histone deacetylase 4 isoform X4 [Octopus sine...
1352,XP_029641181.1,Hist_deacetyl,2.500000e-87,histone deacetylase 4 isoform X1 [Octopus sine...
1349,XP_029641182.1,Hist_deacetyl,2.500000e-87,histone deacetylase 4 isoform X2 [Octopus sine...
1353,XP_029653385.1,Hist_deacetyl,3.500000e-86,histone deacetylase 2 isoform X2 [Octopus sine...
1354,XP_029653384.1,Hist_deacetyl,3.600000e-86,histone deacetylase 2 isoform X1 [Octopus sine...
1355,XP_029648267.1,Hist_deacetyl,3.000000e-85,histone deacetylase 3 [Octopus sinensis]
25,XP_036364112.1,SNF2-rel_dom,7.300000e-83,SWI/SNF-related matrix-associated actin-depend...
26,XP_036364111.1,SNF2-rel_dom,7.300000e-83,SWI/SNF-related matrix-associated actin-depend...
28,XP_036364110.1,SNF2-rel_dom,7.400000e-83,SWI/SNF-related matrix-associated actin-depend...
27,XP_029644034.1,SNF2-rel_dom,7.400000e-83,SWI/SNF-related matrix-associated actin-depend...
29,XP_029644031.1,SNF2-rel_dom,7.600000e-83,SWI/SNF-related matrix-associated actin-depend...
30,XP_036364108.1,SNF2-rel_dom,7.600000e-83,SWI/SNF-related matrix-associated actin-depend...
31,XP_029644033.1,SNF2-rel_dom,7.700000e-83,SWI/SNF-related matrix-associated actin-depend...
32,XP_029644030.1,SNF2-rel_dom,8.100000e-83,SWI/SNF-related matrix-associated actin-depend...
33,XP_029644029.1,SNF2-rel_dom,8.100000e-83,SWI/SNF-related matrix-associated actin-depend...
1356,XP_036366924.1,Hist_deacetyl,4.000000e-82,histone deacetylase 6-like isoform X2 [Octopus...

In [12]:
df.groupby("domain").size().sort_values(ascending=False)

domain
PHD              337
Helicase_C       207
MBD              105
SNF2-rel_dom      88
SET               86
Bromodomain       84
PrmA              63
Chromo            48
DNA_methylase     16
Hist_deacetyl     14
SAD_SRA            2
dtype: int64

In [13]:
df.to_csv(
    "epigenetic_hits.csv",
    index=False
)

df.head(50)

,protein,domain,evalue,description
23,XP_029649198.1,SNF2-rel_dom,5.700000e-90,E3 ubiquitin-protein ligase SHPRH [Octopus sin...
24,XP_036367890.1,SNF2-rel_dom,5.700000e-90,E3 ubiquitin-protein ligase SHPRH [Octopus sin...
1339,XP_029641183.1,Hist_deacetyl,3.000000e-88,histone deacetylase 4 isoform X3 [Octopus sine...
1341,XP_029641185.1,Hist_deacetyl,2.300000e-87,histone deacetylase 4 isoform X5 [Octopus sine...
1344,XP_029641184.1,Hist_deacetyl,2.300000e-87,histone deacetylase 4 isoform X4 [Octopus sine...
1352,XP_029641181.1,Hist_deacetyl,2.500000e-87,histone deacetylase 4 isoform X1 [Octopus sine...
1349,XP_029641182.1,Hist_deacetyl,2.500000e-87,histone deacetylase 4 isoform X2 [Octopus sine...
1353,XP_029653385.1,Hist_deacetyl,3.500000e-86,histone deacetylase 2 isoform X2 [Octopus sine...
1354,XP_029653384.1,Hist_deacetyl,3.600000e-86,histone deacetylase 2 isoform X1 [Octopus sine...
1355,XP_029648267.1,Hist_deacetyl,3.000000e-85,histone deacetylase 3 [Octopus sinensis]
25,XP_036364112.1,SNF2-rel_dom,7.300000e-83,SWI/SNF-related matrix-associated actin-depend...
26,XP_036364111.1,SNF2-rel_dom,7.300000e-83,SWI/SNF-related matrix-associated actin-depend...
28,XP_036364110.1,SNF2-rel_dom,7.400000e-83,SWI/SNF-related matrix-associated actin-depend...
27,XP_029644034.1,SNF2-rel_dom,7.400000e-83,SWI/SNF-related matrix-associated actin-depend...
29,XP_029644031.1,SNF2-rel_dom,7.600000e-83,SWI/SNF-related matrix-associated actin-depend...
30,XP_036364108.1,SNF2-rel_dom,7.600000e-83,SWI/SNF-related matrix-associated actin-depend...
31,XP_029644033.1,SNF2-rel_dom,7.700000e-83,SWI/SNF-related matrix-associated actin-depend...
32,XP_029644030.1,SNF2-rel_dom,8.100000e-83,SWI/SNF-related matrix-associated actin-depend...
33,XP_029644029.1,SNF2-rel_dom,8.100000e-83,SWI/SNF-related matrix-associated actin-depend...
1356,XP_036366924.1,Hist_deacetyl,4.000000e-82,histone deacetylase 6-like isoform X2 [Octopus...
1358,XP_029647709.1,Hist_deacetyl,1.600000e-80,histone deacetylase 6-like isoform X1 [Octopus...
1361,XP_036366923.1,Hist_deacetyl,1.600000e-80,histone deacetylase 6-like isoform X1 [Octopus...
1362,XP_029649631.2,Hist_deacetyl,1.600000e-77,histone deacetylase 8-like [Octopus sinensis]
34,XP_029644245.1,SNF2-rel_dom,7.700000e-74,probable global transcription activator SNF2L2...
35,XP_036364323.1,SNF2-rel_dom,7.900000e-74,probable global transcription activator SNF2L2...
37,XP_029644241.1,SNF2-rel_dom,8.100000e-74,probable global transcription activator SNF2L2...
36,XP_036364322.1,SNF2-rel_dom,8.100000e-74,probable global transcription activator SNF2L2...
38,XP_029644242.1,SNF2-rel_dom,8.100000e-74,probable global transcription activator SNF2L2...
39,XP_029644243.1,SNF2-rel_dom,8.200000e-74,probable global transcription activator SNF2L2...
40,XP_029644244.1,SNF2-rel_dom,3.400000e-73,probable global transcription activator SNF2L2...
42,XP_029648528.1,SNF2-rel_dom,4.200000e-72,LOW QUALITY PROTEIN: helicase domino-like [Oct...
43,XP_036365755.1,SNF2-rel_dom,1.700000e-71,chromodomain-helicase-DNA-binding protein 1 is...
45,XP_029646235.1,SNF2-rel_dom,3.400000e-71,chromodomain-helicase-DNA-binding protein 1 is...
50,XP_029646234.1,SNF2-rel_dom,3.600000e-71,chromodomain-helicase-DNA-binding protein 1 is...
48,XP_029646233.1,SNF2-rel_dom,3.600000e-71,chromodomain-helicase-DNA-binding protein 1 is...
51,XP_036354972.1,SNF2-rel_dom,4.600000e-71,LOW QUALITY PROTEIN: transcription activator B...
52,XP_036354818.1,SNF2-rel_dom,4.900000e-71,LOW QUALITY PROTEIN: probable global transcrip...
53,XP_036371390.1,SNF2-rel_dom,5.700000e-71,LOW QUALITY PROTEIN: ATP-dependent helicase br...
55,XP_029637351.1,SNF2-rel_dom,4.900000e-70,chromatin-remodeling ATPase INO80-like [Octopu...
54,XP_029637350.1,SNF2-rel_dom,4.900000e-70,chromatin-remodeling ATPase INO80-like [Octopu...
56,XP_036366391.1,SNF2-rel_dom,1.300000e-68,lymphocyte-specific helicase-like [Octopus sin...
59,XP_029647192.1,SNF2-rel_dom,6.700000e-67,chromodomain-helicase-DNA-binding protein 8 is...
58,XP_029647193.1,SNF2-rel_dom,6.700000e-67,chromodomain-helicase-DNA-binding protein 8 is...
60,XP_029647190.1,SNF2-rel_dom,6.700000e-67,chromodomain-helicase-DNA-binding protein 8 is...
61,XP_029647191.1,SNF2-rel_dom,6.700000e-67,chromodomain-helicase-DNA-binding protein 8 is...
57,XP_036366325.1,SNF2-rel_dom,6.700000e-67,chromodomain-helicase-DNA-binding protein 8 is...
62,XP_029644186.1,SNF2-rel_dom,1.400000e-66,DNA repair and recombination protein RAD54-lik...
63,XP_029646312.1,SNF2-rel_dom,9.700000e-65,chromodomain-helicase-DNA-binding protein 1-li...
65,XP_036365886.1,SNF2-rel_dom,1.000000e-64,chromodomain-helicase-DNA-binding protein 1-li...
64,XP_036365887.1,SNF2-rel_dom,1.000000e-64,chromodomain-helicase-DNA-binding protein 1-li...

In [14]:
top_hits = (
    df.sort_values("evalue")
      .groupby("domain")
      .head(10)
)

top_hits[
    ["domain", "protein", "evalue", "description"]
].head(100)

,domain,protein,evalue,description
23,SNF2-rel_dom,XP_029649198.1,5.700000e-90,E3 ubiquitin-protein ligase SHPRH [Octopus sin...
24,SNF2-rel_dom,XP_036367890.1,5.700000e-90,E3 ubiquitin-protein ligase SHPRH [Octopus sin...
1339,Hist_deacetyl,XP_029641183.1,3.000000e-88,histone deacetylase 4 isoform X3 [Octopus sine...
1341,Hist_deacetyl,XP_029641185.1,2.300000e-87,histone deacetylase 4 isoform X5 [Octopus sine...
1344,Hist_deacetyl,XP_029641184.1,2.300000e-87,histone deacetylase 4 isoform X4 [Octopus sine...
...,...,...,...,...
1760,PrmA,XP_036357580.1,3.600000e-12,rRNA N6-adenosine-methyltransferase METTL5 [Oc...
1757,PrmA,XP_029641193.1,3.600000e-12,rRNA N6-adenosine-methyltransferase METTL5 [Oc...
1759,PrmA,XP_036357579.1,3.600000e-12,rRNA N6-adenosine-methyltransferase METTL5 [Oc...
1761,PrmA,XP_029641933.1,3.300000e-09,protein arginine N-methyltransferase 6 [Octopu...
1762,PrmA,XP_036357789.1,4.000000e-09,protein arginine N-methyltransferase 1-like is...

In [15]:
for domain in sorted(df["domain"].unique()):
    print()
    print("="*80)
    print(domain)

    tmp = (
        df[df["domain"] == domain]
        .sort_values("evalue")
        [["protein", "evalue", "description"]]
        .head(15)
    )

    display(tmp)

================================================================================
Bromodomain

,protein,evalue,description
451,XP_036370689.1,4.500000e-60,protein polybromo-1 [Octopus sinensis]
456,XP_036370885.1,7.700000e-49,protein polybromo-1 isoform X3 [Octopus sinensis]
458,XP_036370884.1,7.700000e-49,protein polybromo-1 isoform X2 [Octopus sinensis]
462,XP_036370883.1,7.800000e-49,protein polybromo-1 isoform X1 [Octopus sinensis]
463,XP_029658457.1,4.400000e-41,bromodomain-containing protein 3 isoform X5 [O...
465,XP_029658456.1,4.500000e-41,bromodomain-containing protein 3 isoform X4 [O...
467,XP_029658455.1,4.600000e-41,bromodomain-containing protein 3 isoform X3 [O...
472,XP_029658454.1,4.800000e-41,bromodomain-containing protein 3 isoform X1 [O...
470,XP_036355015.1,4.800000e-41,bromodomain-containing protein 3 isoform X2 [O...
473,XP_029649253.1,6.800000e-41,PH-interacting protein isoform X2 [Octopus sin...
476,XP_029649251.1,6.900000e-41,PH-interacting protein isoform X1 [Octopus sin...
477,XP_029644076.1,9.300000e-37,transcription initiation factor TFIID subunit ...
484,XP_036364200.1,9.800000e-37,transcription initiation factor TFIID subunit ...
480,XP_029644075.1,9.800000e-37,transcription initiation factor TFIID subunit ...
482,XP_036364199.1,9.800000e-37,transcription initiation factor TFIID subunit ...

================================================================================
Chromo

,protein,evalue,description
374,XP_036365755.1,7.300000e-23,chromodomain-helicase-DNA-binding protein 1 is...
377,XP_029646233.1,7.700000e-23,chromodomain-helicase-DNA-binding protein 1 is...
378,XP_029646234.1,7.700000e-23,chromodomain-helicase-DNA-binding protein 1 is...
381,XP_029637374.1,3.800000e-22,chromobox protein homolog 1 isoform X2 [Octopu...
384,XP_029637373.1,4.900000e-22,chromobox protein homolog 1 isoform X1 [Octopu...
386,XP_029646235.1,5.700000e-22,chromodomain-helicase-DNA-binding protein 1 is...
389,XP_036366325.1,1.800000e-17,chromodomain-helicase-DNA-binding protein 8 is...
397,XP_029647191.1,1.800000e-17,chromodomain-helicase-DNA-binding protein 8 is...
393,XP_029647192.1,1.800000e-17,chromodomain-helicase-DNA-binding protein 8 is...
395,XP_029647190.1,1.800000e-17,chromodomain-helicase-DNA-binding protein 8 is...
391,XP_029647193.1,1.800000e-17,chromodomain-helicase-DNA-binding protein 8 is...
398,XP_029652203.1,3.900000e-15,uncharacterized protein DDB_G0271670 [Octopus ...
399,XP_029655198.1,8.000000e-15,histone-lysine N-methyltransferase SUV39H2-lik...
400,XP_029651339.1,7.300000e-13,chromodomain-helicase-DNA-binding protein 4 is...
403,XP_029651338.1,7.500000e-13,chromodomain-helicase-DNA-binding protein 4 is...

================================================================================
DNA_methylase

,protein,evalue,description
0,XP_029649765.1,2.200000e-49,DNA (cytosine-5)-methyltransferase 1-like [Oct...
1,XP_029639092.2,1.100000e-41,tRNA (cytosine(38)-C(5))-methyltransferase [Oc...
3,XP_036361613.1,2.000000e-17,DNA (cytosine-5)-methyltransferase 3B isoform ...
7,XP_029641100.1,2.700000e-17,DNA (cytosine-5)-methyltransferase 3B isoform ...
10,XP_036361608.1,2.700000e-17,DNA (cytosine-5)-methyltransferase 3B isoform ...
8,XP_036361607.1,2.700000e-17,DNA (cytosine-5)-methyltransferase 3B isoform ...
13,XP_036361609.1,2.700000e-17,DNA (cytosine-5)-methyltransferase 3B isoform ...
5,XP_036361611.1,2.700000e-17,DNA (cytosine-5)-methyltransferase 3B isoform ...
15,XP_036361610.1,2.700000e-17,DNA (cytosine-5)-methyltransferase 3B isoform ...
16,XP_036361612.1,1.800000e-14,DNA (cytosine-5)-methyltransferase 3B isoform ...
20,XP_036357580.1,2.000000e-02,rRNA N6-adenosine-methyltransferase METTL5 [Oc...
17,XP_029641193.1,2.000000e-02,rRNA N6-adenosine-methyltransferase METTL5 [Oc...
19,XP_036357579.1,2.000000e-02,rRNA N6-adenosine-methyltransferase METTL5 [Oc...
18,XP_029641194.1,2.000000e-02,rRNA N6-adenosine-methyltransferase METTL5 [Oc...
21,XP_029639525.1,7.100000e-02,electron transfer flavoprotein beta subunit ly...

================================================================================
Helicase_C

,protein,evalue,description
120,XP_029647935.1,5.200000e-32,ATP-dependent RNA helicase eIF4A [Octopus sine...
121,XP_029643309.1,6.400000e-32,eukaryotic initiation factor 4A-III [Octopus s...
126,XP_029650465.1,1.600000e-31,probable ATP-dependent RNA helicase DDX43 isof...
124,XP_029650466.1,1.600000e-31,probable ATP-dependent RNA helicase DDX43 isof...
128,XP_029650464.1,1.700000e-31,probable ATP-dependent RNA helicase DDX43 isof...
130,XP_029650463.1,1.700000e-31,probable ATP-dependent RNA helicase DDX43 isof...
131,XP_029638292.2,2.000000e-31,probable ATP-dependent RNA helicase DDX47 isof...
132,XP_036360192.1,2.400000e-31,probable ATP-dependent RNA helicase DDX47 isof...
133,XP_029647974.1,2.900000e-31,ATP-dependent RNA helicase eIF4A [Octopus sine...
134,XP_029641876.1,3.500000e-31,ATP-dependent RNA helicase DDX3X isoform X4 [O...
135,XP_029641875.1,3.800000e-31,ATP-dependent RNA helicase DDX3X isoform X3 [O...
136,XP_029649676.1,3.900000e-31,probable ATP-dependent RNA helicase DDX41 [Oct...
137,XP_029641873.1,4.100000e-31,ATP-dependent RNA helicase DDX3X isoform X2 [O...
138,XP_029641872.1,4.400000e-31,putative ATP-dependent RNA helicase Pl10 isofo...
139,XP_029633378.1,4.700000e-31,probable ATP-dependent RNA helicase DDX4 isofo...

================================================================================
Hist_deacetyl

,protein,evalue,description
1339,XP_029641183.1,3.000000e-88,histone deacetylase 4 isoform X3 [Octopus sine...
1341,XP_029641185.1,2.300000e-87,histone deacetylase 4 isoform X5 [Octopus sine...
1344,XP_029641184.1,2.300000e-87,histone deacetylase 4 isoform X4 [Octopus sine...
1352,XP_029641181.1,2.500000e-87,histone deacetylase 4 isoform X1 [Octopus sine...
1349,XP_029641182.1,2.500000e-87,histone deacetylase 4 isoform X2 [Octopus sine...
1353,XP_029653385.1,3.500000e-86,histone deacetylase 2 isoform X2 [Octopus sine...
1354,XP_029653384.1,3.600000e-86,histone deacetylase 2 isoform X1 [Octopus sine...
1355,XP_029648267.1,3.000000e-85,histone deacetylase 3 [Octopus sinensis]
1356,XP_036366924.1,4.000000e-82,histone deacetylase 6-like isoform X2 [Octopus...
1358,XP_029647709.1,1.600000e-80,histone deacetylase 6-like isoform X1 [Octopus...
1361,XP_036366923.1,1.600000e-80,histone deacetylase 6-like isoform X1 [Octopus...
1362,XP_029649631.2,1.600000e-77,histone deacetylase 8-like [Octopus sinensis]
1363,XP_029635168.1,3.700000e-46,histone deacetylase 11 isoform X2 [Octopus sin...
1364,XP_029635167.1,7.700000e-46,histone deacetylase 11 isoform X1 [Octopus sin...

================================================================================
MBD

,protein,evalue,description
1516,XP_029646213.1,1.100000e-25,methyl-CpG-binding domain protein 2 isoform X3...
1519,XP_036366011.1,1.200000e-25,methyl-CpG-binding domain protein 2 isoform X1...
1518,XP_029646212.1,1.200000e-25,methyl-CpG-binding domain protein 2 isoform X2...
1521,XP_036366012.1,1.200000e-25,methyl-CpG-binding domain protein 2 isoform X1...
1523,XP_029646214.1,2.200000e-25,methyl-CpG-binding domain protein 2 isoform X4...
1525,XP_029647369.1,1.900000e-14,methyl-CpG-binding domain protein 4 [Octopus s...
1534,XP_029646824.1,8.000000e-14,bromodomain adjacent to zinc finger domain pro...
1538,XP_036366362.1,8.000000e-14,bromodomain adjacent to zinc finger domain pro...
1537,XP_036366361.1,8.000000e-14,bromodomain adjacent to zinc finger domain pro...
1526,XP_029646828.1,8.000000e-14,bromodomain adjacent to zinc finger domain pro...
1527,XP_029646826.1,8.000000e-14,bromodomain adjacent to zinc finger domain pro...
1533,XP_029646823.1,8.000000e-14,bromodomain adjacent to zinc finger domain pro...
1535,XP_036366359.1,8.000000e-14,bromodomain adjacent to zinc finger domain pro...
1532,XP_029646822.1,8.000000e-14,bromodomain adjacent to zinc finger domain pro...
1528,XP_029646827.1,8.000000e-14,bromodomain adjacent to zinc finger domain pro...

================================================================================
PHD

,protein,evalue,description
555,XP_036356891.1,4.300000e-40,uncharacterized protein LOC115209744 isoform X...
561,XP_036356890.1,4.500000e-40,uncharacterized protein LOC115209744 isoform X...
567,XP_036356889.1,4.800000e-40,uncharacterized protein LOC115209744 isoform X...
574,XP_036356888.1,4.800000e-40,uncharacterized protein LOC115209744 isoform X...
586,XP_036356886.1,4.900000e-40,uncharacterized protein LOC115209744 isoform X...
579,XP_036356887.1,4.900000e-40,uncharacterized protein LOC115209744 isoform X...
591,XP_036356885.1,5.000000e-40,uncharacterized protein LOC115209744 isoform X...
601,XP_036356884.1,5.200000e-40,uncharacterized protein LOC115209744 isoform X...
606,XP_029634114.2,5.300000e-40,uncharacterized protein LOC115209744 isoform X...
611,XP_036356892.1,2.000000e-37,uncharacterized protein LOC115209744 isoform X...
614,XP_029635776.1,9.300000e-26,nucleosome-remodeling factor subunit BPTF isof...
617,XP_029635778.1,9.400000e-26,nucleosome-remodeling factor subunit BPTF isof...
621,XP_029635777.1,1.000000e-25,nucleosome-remodeling factor subunit BPTF isof...
626,XP_029650864.1,2.100000e-23,bromodomain adjacent to zinc finger domain pro...
623,XP_036369343.1,2.100000e-23,bromodomain adjacent to zinc finger domain pro...

================================================================================
PrmA

,protein,evalue,description
1754,XP_029639525.1,4.300000e-13,electron transfer flavoprotein beta subunit ly...
1755,XP_029637505.1,4.500000e-13,protein arginine N-methyltransferase 7 [Octopu...
1759,XP_036357579.1,3.600000e-12,rRNA N6-adenosine-methyltransferase METTL5 [Oc...
1758,XP_029641194.1,3.600000e-12,rRNA N6-adenosine-methyltransferase METTL5 [Oc...
1757,XP_029641193.1,3.600000e-12,rRNA N6-adenosine-methyltransferase METTL5 [Oc...
1760,XP_036357580.1,3.600000e-12,rRNA N6-adenosine-methyltransferase METTL5 [Oc...
1761,XP_029641933.1,3.300000e-09,protein arginine N-methyltransferase 6 [Octopu...
1762,XP_036357789.1,4.000000e-09,protein arginine N-methyltransferase 1-like is...
1765,XP_029635578.2,4.600000e-09,protein arginine N-methyltransferase 1-like is...
1767,XP_036357790.1,4.600000e-09,protein arginine N-methyltransferase 1-like is...
1768,XP_029638714.1,3.000000e-08,protein arginine N-methyltransferase 1 isoform...
1769,XP_029638713.1,3.000000e-08,protein arginine N-methyltransferase 1 isoform...
1770,XP_029638712.1,3.300000e-08,protein arginine N-methyltransferase 1 isoform...
1771,XP_029654200.2,9.200000e-08,"uncharacterized protein LOC115227545, partial ..."
1772,XP_029654369.1,1.100000e-07,"ubiquinone biosynthesis O-methyltransferase, m..."

================================================================================
SAD_SRA

,protein,evalue,description
1751,XP_029637720.1,6.800000e-58,E3 ubiquitin-protein ligase UHRF1-like [Octopu...
1752,XP_029639941.1,4.600000e-57,E3 ubiquitin-protein ligase UHRF1 [Octopus sin...

================================================================================
SET

,protein,evalue,description
1365,XP_036360314.1,2.700000e-28,histone-lysine N-methyltransferase SETDB1 isof...
1369,XP_036360312.1,3.000000e-28,histone-lysine N-methyltransferase SETDB1 isof...
1374,XP_036360310.1,3.400000e-28,histone-lysine N-methyltransferase SETDB1 isof...
1371,XP_036360311.1,3.400000e-28,histone-lysine N-methyltransferase SETDB1 isof...
1377,XP_029649008.1,2.000000e-23,histone-lysine N-methyltransferase EHMT2 isofo...
1378,XP_029649006.1,2.600000e-23,histone-lysine N-methyltransferase EHMT2 isofo...
1379,XP_029649007.1,5.700000e-23,histone-lysine N-methyltransferase EHMT2 isofo...
1381,XP_029647319.1,2.200000e-22,histone-lysine N-methyltransferase 2A isoform ...
1387,XP_029647318.1,2.200000e-22,histone-lysine N-methyltransferase 2A isoform ...
1384,XP_029647321.1,2.200000e-22,histone-lysine N-methyltransferase 2A isoform ...
1383,XP_029647320.1,2.200000e-22,histone-lysine N-methyltransferase 2A isoform ...
1388,XP_029655198.1,5.800000e-22,histone-lysine N-methyltransferase SUV39H2-lik...
1390,XP_029651312.1,1.600000e-21,N-lysine methyltransferase SETD6 [Octopus sine...
1393,XP_029645712.1,3.100000e-19,histone-lysine N-methyltransferase EZH2 isofor...
1394,XP_029645687.1,3.200000e-19,histone-lysine N-methyltransferase EZH2 isofor...

================================================================================
SNF2-rel_dom

,protein,evalue,description
23,XP_029649198.1,5.700000e-90,E3 ubiquitin-protein ligase SHPRH [Octopus sin...
24,XP_036367890.1,5.700000e-90,E3 ubiquitin-protein ligase SHPRH [Octopus sin...
25,XP_036364112.1,7.300000e-83,SWI/SNF-related matrix-associated actin-depend...
26,XP_036364111.1,7.300000e-83,SWI/SNF-related matrix-associated actin-depend...
28,XP_036364110.1,7.400000e-83,SWI/SNF-related matrix-associated actin-depend...
27,XP_029644034.1,7.400000e-83,SWI/SNF-related matrix-associated actin-depend...
29,XP_029644031.1,7.600000e-83,SWI/SNF-related matrix-associated actin-depend...
30,XP_036364108.1,7.600000e-83,SWI/SNF-related matrix-associated actin-depend...
31,XP_029644033.1,7.700000e-83,SWI/SNF-related matrix-associated actin-depend...
32,XP_029644030.1,8.100000e-83,SWI/SNF-related matrix-associated actin-depend...
33,XP_029644029.1,8.100000e-83,SWI/SNF-related matrix-associated actin-depend...
34,XP_029644245.1,7.700000e-74,probable global transcription activator SNF2L2...
35,XP_036364323.1,7.900000e-74,probable global transcription activator SNF2L2...
37,XP_029644241.1,8.100000e-74,probable global transcription activator SNF2L2...
36,XP_036364322.1,8.100000e-74,probable global transcription activator SNF2L2...

In [17]:
feature_table = pd.read_csv(
    "/content/GCF_006345805.1_ASM634580v1_feature_table.txt",
    sep="\t",
    low_memory=False
)

print(feature_table.columns.tolist())

['# feature', 'class', 'assembly', 'assembly_unit', 'seq_type', 'chromosome', 'genomic_accession', 'start', 'end', 'strand', 'product_accession', 'non-redundant_refseq', 'related_accession', 'name', 'symbol', 'GeneID', 'locus_tag', 'feature_interval_length', 'product_length', 'attributes']

In [18]:
selected_genes = [
    "DNA (cytosine-5)-methyltransferase 1",
    "DNA (cytosine-5)-methyltransferase 3B",
    "UHRF1",
    "methyl-CpG-binding domain protein 2",
    "histone deacetylase 4",
    "histone deacetylase 2",
    "histone deacetylase 3",
    "histone deacetylase 6",
    "SETDB1",
    "EHMT2",
    "EZH2",
    "SUV39H2",
    "protein arginine N-methyltransferase 1",
    "protein arginine N-methyltransferase 6",
    "protein polybromo-1",
    "chromodomain-helicase-DNA-binding protein 1",
    "SWI/SNF-related matrix-associated actin-dependent regulator"
]

In [19]:
feature_table = pd.read_csv(
    "/content/GCF_006345805.1_ASM634580v1_feature_table.txt",
    sep="\t",
    low_memory=False
)

feature_table = feature_table.fillna("")

matches = []

for gene in selected_genes:
    mask = (
        feature_table["name"].str.contains(
            gene,
            case=False,
            regex=False
        )
    )

    found = feature_table[mask]

    if len(found):
        matches.append(
            found[
                [
                    "name",
                    "symbol",
                    "chromosome",
                    "genomic_accession",
                    "start",
                    "end",
                    "strand",
                    "GeneID"
                ]
            ]
        )

result = pd.concat(matches)

result.drop_duplicates().head(100)

,name,symbol,chromosome,genomic_accession,start,end,strand,GeneID
81977,DNA (cytosine-5)-methyltransferase 1-like,LOC115223392,LG23,NC_043019.1,5188422,5277167,-,115223392.0
81978,DNA (cytosine-5)-methyltransferase 1-like,LOC115223392,LG23,NC_043019.1,5188454,5276864,-,115223392.0
43992,"DNA (cytosine-5)-methyltransferase 3B, transcr...",LOC115215890,LG9,NC_043005.1,866019,972656,+,115215890.0
43993,"DNA (cytosine-5)-methyltransferase 3B, transcr...",LOC115215890,LG9,NC_043005.1,876508,972656,+,115215890.0
43994,"DNA (cytosine-5)-methyltransferase 3B, transcr...",LOC115215890,LG9,NC_043005.1,876699,972656,+,115215890.0
...,...,...,...,...,...,...,...,...
21421,"protein arginine N-methyltransferase 1-like, t...",LOC115210929,LG4,NC_043000.1,22341094,22361754,-,115210929.0
21422,"protein arginine N-methyltransferase 1-like, t...",LOC115210929,LG4,NC_043000.1,22341094,22347280,-,115210929.0
21423,protein arginine N-methyltransferase 1-like is...,LOC115210929,LG4,NC_043000.1,22342604,22361675,-,115210929.0
21424,protein arginine N-methyltransferase 1-like is...,LOC115210929,LG4,NC_043000.1,22342604,22343962,-,115210929.0
37581,"protein arginine N-methyltransferase 1, transc...",LOC115213886,LG7,NC_043003.1,27400128,27442929,+,115213886.0

In [20]:
print(result.shape)
result.head(20)

(276, 8)

,name,symbol,chromosome,genomic_accession,start,end,strand,GeneID
81977,DNA (cytosine-5)-methyltransferase 1-like,LOC115223392,LG23,NC_043019.1,5188422,5277167,-,115223392.0
81978,DNA (cytosine-5)-methyltransferase 1-like,LOC115223392,LG23,NC_043019.1,5188454,5276864,-,115223392.0
43992,"DNA (cytosine-5)-methyltransferase 3B, transcr...",LOC115215890,LG9,NC_043005.1,866019,972656,+,115215890.0
43993,"DNA (cytosine-5)-methyltransferase 3B, transcr...",LOC115215890,LG9,NC_043005.1,876508,972656,+,115215890.0
43994,"DNA (cytosine-5)-methyltransferase 3B, transcr...",LOC115215890,LG9,NC_043005.1,876699,972656,+,115215890.0
43995,"DNA (cytosine-5)-methyltransferase 3B, transcr...",LOC115215890,LG9,NC_043005.1,876705,972656,+,115215890.0
43996,"DNA (cytosine-5)-methyltransferase 3B, transcr...",LOC115215890,LG9,NC_043005.1,876707,972656,+,115215890.0
43997,"DNA (cytosine-5)-methyltransferase 3B, transcr...",LOC115215890,LG9,NC_043005.1,876710,972656,+,115215890.0
43998,DNA (cytosine-5)-methyltransferase 3B isoform X4,LOC115215890,LG9,NC_043005.1,876841,972446,+,115215890.0
43999,"DNA (cytosine-5)-methyltransferase 3B, transcr...",LOC115215890,LG9,NC_043005.1,877585,972656,+,115215890.0
44000,"DNA (cytosine-5)-methyltransferase 3B, transcr...",LOC115215890,LG9,NC_043005.1,897663,972656,+,115215890.0
44001,DNA (cytosine-5)-methyltransferase 3B isoform X1,LOC115215890,LG9,NC_043005.1,899804,972446,+,115215890.0
44002,DNA (cytosine-5)-methyltransferase 3B isoform X1,LOC115215890,LG9,NC_043005.1,899804,972446,+,115215890.0
44003,DNA (cytosine-5)-methyltransferase 3B isoform X1,LOC115215890,LG9,NC_043005.1,899804,972446,+,115215890.0
44004,DNA (cytosine-5)-methyltransferase 3B isoform X1,LOC115215890,LG9,NC_043005.1,899804,972446,+,115215890.0
44005,DNA (cytosine-5)-methyltransferase 3B isoform X1,LOC115215890,LG9,NC_043005.1,899804,972446,+,115215890.0
44006,DNA (cytosine-5)-methyltransferase 3B isoform X2,LOC115215890,LG9,NC_043005.1,899804,972446,+,115215890.0
44007,DNA (cytosine-5)-methyltransferase 3B isoform X3,LOC115215890,LG9,NC_043005.1,899804,972396,+,115215890.0
17198,"UHRF1-binding protein 1-like, transcript varia...",LOC115209824,LG3,NC_042999.1,90125217,90215792,+,115209824.0
17199,"UHRF1-binding protein 1-like, transcript varia...",LOC115209824,LG3,NC_042999.1,90125218,90215792,+,115209824.0

In [23]:
result["gene_length"] = result["end"] - result["start"]

result_unique = (
    result
    .sort_values("gene_length", ascending=False)
    .drop_duplicates(subset=["GeneID"])
)

print(result_unique.shape)

result_unique[
    [
        "name",
        "symbol",
        "chromosome",
        "start",
        "end",
        "gene_length"
    ]
]

(30, 9)

,name,symbol,chromosome,start,end,gene_length
47016,"histone deacetylase 4, transcript variant X1",LOC115215943,LG9,92930807,93266672,335865
5878,"histone-lysine N-methyltransferase EZH2, trans...",LOC115219651,LG1,172419133,172619352,200219
93845,protein polybromo-1,LOC115226006,LG29,6932683,7048225,115542
93850,"protein polybromo-1, transcript variant X1",LOC115225947,LG29,7092277,7205862,113585
67347,"chromodomain-helicase-DNA-binding protein 1, t...",LOC115220266,LG16,5509439,5618186,108747
43992,"DNA (cytosine-5)-methyltransferase 3B, transcr...",LOC115215890,LG9,866019,972656,106637
48893,SWI/SNF-related matrix-associated actin-depend...,LOC115216480,LG10,33333147,33426805,93658
17198,"UHRF1-binding protein 1-like, transcript varia...",LOC115209824,LG3,90125217,90215792,90575
81977,DNA (cytosine-5)-methyltransferase 1-like,LOC115223392,LG23,5188422,5277167,88745
36215,"histone-lysine N-methyltransferase SETDB1, tra...",LOC115213825,LG7,33277,108805,75528
74455,"histone deacetylase 6-like, transcript variant X2",LOC115221647,LG18,49248748,49323286,74538
68391,chromodomain-helicase-DNA-binding protein 1-li...,LOC115220346,LG16,35431570,35500111,68541
43232,E3 ubiquitin-protein ligase UHRF1,LOC115214982,LG8,86870253,86934621,64368
68914,"methyl-CpG-binding domain protein 2, transcrip...",LOC115220257,LG16,44577456,44632430,54974
79510,"histone-lysine N-methyltransferase EHMT2, tran...",LOC115222829,LG21,15535853,15589518,53665
80432,SWI/SNF-related matrix-associated actin-depend...,LOC115223208,LG22,4766862,4820425,53563
75200,histone deacetylase 3,LOC115222249,LG19,16943813,16996831,53018
58284,SWI/SNF-related matrix-associated actin-depend...,LOC115218388,LG13,22963351,23014309,50958
37581,"protein arginine N-methyltransferase 1, transc...",LOC115213886,LG7,27400128,27442929,42801
21420,"protein arginine N-methyltransferase 1-like, t...",LOC115210929,LG4,22341094,22383015,41921
95861,"histone deacetylase 2, transcript variant X1",LOC115226524,LG30,10858998,10897673,38675
50603,SWI/SNF-related matrix-associated actin-depend...,LOC115216406,LG10,71909430,71943990,34560
35665,E3 ubiquitin-protein ligase UHRF1-like,LOC115212993,LG6,109087823,109114905,27082
50581,protein arginine N-methyltransferase 6,LOC115216599,LG10,71785460,71811453,25993
102585,histone-lysine N-methyltransferase SUV39H2-like,LOC115228866,,66472,86532,20060
20035,"histone deacetylase 6, transcript variant X1",LOC115209433,LG3,166080823,166100110,19287
77627,SWI/SNF-related matrix-associated actin-depend...,LOC115222565,LG20,15103397,15120929,17532
97124,histone-lysine N-methyltransferase SETDB1-A-like,LOC118768672,,9199,13349,4150
111417,SWI/SNF-related matrix-associated actin-depend...,LOC118761937,,300068,304177,4109
101195,LOW QUALITY PROTEIN: protein arginine N-methyl...,LOC115228326,,29182,30058,876

In [24]:
print("Всего строк:", len(result))
print("Уникальных GeneID:", result["GeneID"].nunique())

Всего строк: 276
Уникальных GeneID: 30

In [25]:
final_table = result_unique[
    [
        "name",
        "symbol",
        "chromosome",
        "genomic_accession",
        "start",
        "end",
        "strand",
        "GeneID",
    ]
].copy()

final_table = final_table.rename(columns={
    "name": "Gene name",
    "symbol": "Gene symbol",
    "chromosome": "Chromosome",
    "genomic_accession": "Accession",
    "start": "Start",
    "end": "End",
    "strand": "Strand",
})

final_table.to_csv("epigenetic_genes_final.tsv", sep="\t", index=False)

final_table

,Gene name,Gene symbol,Chromosome,Accession,Start,End,Strand,GeneID
47016,"histone deacetylase 4, transcript variant X1",LOC115215943,LG9,NC_043005.1,92930807,93266672,+,115215943.0
5878,"histone-lysine N-methyltransferase EZH2, trans...",LOC115219651,LG1,NC_042997.1,172419133,172619352,+,115219651.0
93845,protein polybromo-1,LOC115226006,LG29,NC_043025.1,6932683,7048225,-,115226006.0
93850,"protein polybromo-1, transcript variant X1",LOC115225947,LG29,NC_043025.1,7092277,7205862,+,115225947.0
67347,"chromodomain-helicase-DNA-binding protein 1, t...",LOC115220266,LG16,NC_043012.1,5509439,5618186,-,115220266.0
43992,"DNA (cytosine-5)-methyltransferase 3B, transcr...",LOC115215890,LG9,NC_043005.1,866019,972656,+,115215890.0
48893,SWI/SNF-related matrix-associated actin-depend...,LOC115216480,LG10,NC_043006.1,33333147,33426805,-,115216480.0
17198,"UHRF1-binding protein 1-like, transcript varia...",LOC115209824,LG3,NC_042999.1,90125217,90215792,+,115209824.0
81977,DNA (cytosine-5)-methyltransferase 1-like,LOC115223392,LG23,NC_043019.1,5188422,5277167,-,115223392.0
36215,"histone-lysine N-methyltransferase SETDB1, tra...",LOC115213825,LG7,NC_043003.1,33277,108805,+,115213825.0
74455,"histone deacetylase 6-like, transcript variant X2",LOC115221647,LG18,NC_043014.1,49248748,49323286,+,115221647.0
68391,chromodomain-helicase-DNA-binding protein 1-li...,LOC115220346,LG16,NC_043012.1,35431570,35500111,+,115220346.0
43232,E3 ubiquitin-protein ligase UHRF1,LOC115214982,LG8,NC_043004.1,86870253,86934621,+,115214982.0
68914,"methyl-CpG-binding domain protein 2, transcrip...",LOC115220257,LG16,NC_043012.1,44577456,44632430,+,115220257.0
79510,"histone-lysine N-methyltransferase EHMT2, tran...",LOC115222829,LG21,NC_043017.1,15535853,15589518,-,115222829.0
80432,SWI/SNF-related matrix-associated actin-depend...,LOC115223208,LG22,NC_043018.1,4766862,4820425,+,115223208.0
75200,histone deacetylase 3,LOC115222249,LG19,NC_043015.1,16943813,16996831,+,115222249.0
58284,SWI/SNF-related matrix-associated actin-depend...,LOC115218388,LG13,NC_043009.1,22963351,23014309,-,115218388.0
37581,"protein arginine N-methyltransferase 1, transc...",LOC115213886,LG7,NC_043003.1,27400128,27442929,+,115213886.0
21420,"protein arginine N-methyltransferase 1-like, t...",LOC115210929,LG4,NC_043000.1,22341094,22383015,-,115210929.0
95861,"histone deacetylase 2, transcript variant X1",LOC115226524,LG30,NC_043026.1,10858998,10897673,+,115226524.0
50603,SWI/SNF-related matrix-associated actin-depend...,LOC115216406,LG10,NC_043006.1,71909430,71943990,-,115216406.0
35665,E3 ubiquitin-protein ligase UHRF1-like,LOC115212993,LG6,NC_043002.1,109087823,109114905,+,115212993.0
50581,protein arginine N-methyltransferase 6,LOC115216599,LG10,NC_043006.1,71785460,71811453,+,115216599.0
102585,histone-lysine N-methyltransferase SUV39H2-like,LOC115228866,,NW_021832281.1,66472,86532,-,115228866.0
20035,"histone deacetylase 6, transcript variant X1",LOC115209433,LG3,NC_042999.1,166080823,166100110,-,115209433.0
77627,SWI/SNF-related matrix-associated actin-depend...,LOC115222565,LG20,NC_043016.1,15103397,15120929,+,115222565.0
97124,histone-lysine N-methyltransferase SETDB1-A-like,LOC118768672,,NW_021824334.1,9199,13349,+,118768672.0
111417,SWI/SNF-related matrix-associated actin-depend...,LOC118761937,,NW_021835993.1,300068,304177,-,118761937.0
101195,LOW QUALITY PROTEIN: protein arginine N-methyl...,LOC115228326,,NW_021832120.1,29182,30058,-,115228326.0

In [26]:
df.to_csv("epigenetic_hmmer_hits_all.csv", index=False)

In [27]:
clean_final_table = final_table[
    ~final_table["Gene name"].str.contains(
        "LOW QUALITY|UHRF1-binding|SETDB1-A-like",
        case=False,
        regex=True
    )
].copy()

clean_final_table.to_csv("epigenetic_genes_final_clean.tsv", sep="\t", index=False)

clean_final_table

,Gene name,Gene symbol,Chromosome,Accession,Start,End,Strand,GeneID
47016,"histone deacetylase 4, transcript variant X1",LOC115215943,LG9,NC_043005.1,92930807,93266672,+,115215943.0
5878,"histone-lysine N-methyltransferase EZH2, trans...",LOC115219651,LG1,NC_042997.1,172419133,172619352,+,115219651.0
93845,protein polybromo-1,LOC115226006,LG29,NC_043025.1,6932683,7048225,-,115226006.0
93850,"protein polybromo-1, transcript variant X1",LOC115225947,LG29,NC_043025.1,7092277,7205862,+,115225947.0
67347,"chromodomain-helicase-DNA-binding protein 1, t...",LOC115220266,LG16,NC_043012.1,5509439,5618186,-,115220266.0
43992,"DNA (cytosine-5)-methyltransferase 3B, transcr...",LOC115215890,LG9,NC_043005.1,866019,972656,+,115215890.0
48893,SWI/SNF-related matrix-associated actin-depend...,LOC115216480,LG10,NC_043006.1,33333147,33426805,-,115216480.0
81977,DNA (cytosine-5)-methyltransferase 1-like,LOC115223392,LG23,NC_043019.1,5188422,5277167,-,115223392.0
36215,"histone-lysine N-methyltransferase SETDB1, tra...",LOC115213825,LG7,NC_043003.1,33277,108805,+,115213825.0
74455,"histone deacetylase 6-like, transcript variant X2",LOC115221647,LG18,NC_043014.1,49248748,49323286,+,115221647.0
68391,chromodomain-helicase-DNA-binding protein 1-li...,LOC115220346,LG16,NC_043012.1,35431570,35500111,+,115220346.0
43232,E3 ubiquitin-protein ligase UHRF1,LOC115214982,LG8,NC_043004.1,86870253,86934621,+,115214982.0
68914,"methyl-CpG-binding domain protein 2, transcrip...",LOC115220257,LG16,NC_043012.1,44577456,44632430,+,115220257.0
79510,"histone-lysine N-methyltransferase EHMT2, tran...",LOC115222829,LG21,NC_043017.1,15535853,15589518,-,115222829.0
80432,SWI/SNF-related matrix-associated actin-depend...,LOC115223208,LG22,NC_043018.1,4766862,4820425,+,115223208.0
75200,histone deacetylase 3,LOC115222249,LG19,NC_043015.1,16943813,16996831,+,115222249.0
58284,SWI/SNF-related matrix-associated actin-depend...,LOC115218388,LG13,NC_043009.1,22963351,23014309,-,115218388.0
37581,"protein arginine N-methyltransferase 1, transc...",LOC115213886,LG7,NC_043003.1,27400128,27442929,+,115213886.0
21420,"protein arginine N-methyltransferase 1-like, t...",LOC115210929,LG4,NC_043000.1,22341094,22383015,-,115210929.0
95861,"histone deacetylase 2, transcript variant X1",LOC115226524,LG30,NC_043026.1,10858998,10897673,+,115226524.0
50603,SWI/SNF-related matrix-associated actin-depend...,LOC115216406,LG10,NC_043006.1,71909430,71943990,-,115216406.0
35665,E3 ubiquitin-protein ligase UHRF1-like,LOC115212993,LG6,NC_043002.1,109087823,109114905,+,115212993.0
50581,protein arginine N-methyltransferase 6,LOC115216599,LG10,NC_043006.1,71785460,71811453,+,115216599.0
102585,histone-lysine N-methyltransferase SUV39H2-like,LOC115228866,,NW_021832281.1,66472,86532,-,115228866.0
20035,"histone deacetylase 6, transcript variant X1",LOC115209433,LG3,NC_042999.1,166080823,166100110,-,115209433.0
77627,SWI/SNF-related matrix-associated actin-depend...,LOC115222565,LG20,NC_043016.1,15103397,15120929,+,115222565.0
111417,SWI/SNF-related matrix-associated actin-depend...,LOC118761937,,NW_021835993.1,300068,304177,-,118761937.0

In [28]:
clean_final_table = clean_final_table[
    clean_final_table["Chromosome"] != ""
].copy()

clean_final_table.to_csv("epigenetic_genes_final_clean.tsv", sep="\t", index=False)

clean_final_table

,Gene name,Gene symbol,Chromosome,Accession,Start,End,Strand,GeneID
47016,"histone deacetylase 4, transcript variant X1",LOC115215943,LG9,NC_043005.1,92930807,93266672,+,115215943.0
5878,"histone-lysine N-methyltransferase EZH2, trans...",LOC115219651,LG1,NC_042997.1,172419133,172619352,+,115219651.0
93845,protein polybromo-1,LOC115226006,LG29,NC_043025.1,6932683,7048225,-,115226006.0
93850,"protein polybromo-1, transcript variant X1",LOC115225947,LG29,NC_043025.1,7092277,7205862,+,115225947.0
67347,"chromodomain-helicase-DNA-binding protein 1, t...",LOC115220266,LG16,NC_043012.1,5509439,5618186,-,115220266.0
43992,"DNA (cytosine-5)-methyltransferase 3B, transcr...",LOC115215890,LG9,NC_043005.1,866019,972656,+,115215890.0
48893,SWI/SNF-related matrix-associated actin-depend...,LOC115216480,LG10,NC_043006.1,33333147,33426805,-,115216480.0
81977,DNA (cytosine-5)-methyltransferase 1-like,LOC115223392,LG23,NC_043019.1,5188422,5277167,-,115223392.0
36215,"histone-lysine N-methyltransferase SETDB1, tra...",LOC115213825,LG7,NC_043003.1,33277,108805,+,115213825.0
74455,"histone deacetylase 6-like, transcript variant X2",LOC115221647,LG18,NC_043014.1,49248748,49323286,+,115221647.0
68391,chromodomain-helicase-DNA-binding protein 1-li...,LOC115220346,LG16,NC_043012.1,35431570,35500111,+,115220346.0
43232,E3 ubiquitin-protein ligase UHRF1,LOC115214982,LG8,NC_043004.1,86870253,86934621,+,115214982.0
68914,"methyl-CpG-binding domain protein 2, transcrip...",LOC115220257,LG16,NC_043012.1,44577456,44632430,+,115220257.0
79510,"histone-lysine N-methyltransferase EHMT2, tran...",LOC115222829,LG21,NC_043017.1,15535853,15589518,-,115222829.0
80432,SWI/SNF-related matrix-associated actin-depend...,LOC115223208,LG22,NC_043018.1,4766862,4820425,+,115223208.0
75200,histone deacetylase 3,LOC115222249,LG19,NC_043015.1,16943813,16996831,+,115222249.0
58284,SWI/SNF-related matrix-associated actin-depend...,LOC115218388,LG13,NC_043009.1,22963351,23014309,-,115218388.0
37581,"protein arginine N-methyltransferase 1, transc...",LOC115213886,LG7,NC_043003.1,27400128,27442929,+,115213886.0
21420,"protein arginine N-methyltransferase 1-like, t...",LOC115210929,LG4,NC_043000.1,22341094,22383015,-,115210929.0
95861,"histone deacetylase 2, transcript variant X1",LOC115226524,LG30,NC_043026.1,10858998,10897673,+,115226524.0
50603,SWI/SNF-related matrix-associated actin-depend...,LOC115216406,LG10,NC_043006.1,71909430,71943990,-,115216406.0
35665,E3 ubiquitin-protein ligase UHRF1-like,LOC115212993,LG6,NC_043002.1,109087823,109114905,+,115212993.0
50581,protein arginine N-methyltransferase 6,LOC115216599,LG10,NC_043006.1,71785460,71811453,+,115216599.0
20035,"histone deacetylase 6, transcript variant X1",LOC115209433,LG3,NC_042999.1,166080823,166100110,-,115209433.0
77627,SWI/SNF-related matrix-associated actin-depend...,LOC115222565,LG20,NC_043016.1,15103397,15120929,+,115222565.0